### ISSUE TITLE
boolean?

### ISSUE THREAD

**Issue by moltar** [moodysalem/jointz#8]
Was looking to add this to [typescript-runtime-type-benchmarks](https://github.com/moltar/typescript-runtime-type-benchmarks), but it seems to be missing a boolean validator.

Will you be adding that?

Thanks.

**Comment by moodysalem** [comment]
`jointz.constant(true,false)` should give you that, but I can add an alias

**Comment by moltar** [comment]
Ok, cool, that works!

**Comment by moodysalem** [comment]
5.2.0 has `jointz.boolean()`
